version: '2.0'

services: 
  pp-sponsorship:
    container_name: pp-sponsorship
    build: 
      context: .
    networks: 
      static:
        ipv4_address: 172.19.0.13 
    environment:
      SERVICE_NAME: pp-sponsorship
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/html
    ports:
      - "81:80"
      - "443:443"

  mysql:
    container_name: pp-sponsorship-db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sponsorship
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      static:
        ipv4_address: 172.19.0.14 
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"

#Docker Networks
networks:
  static:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.13/20 

#Volumes
volumes:
  dbdata:
    driver: local